name: Build events.ics daily

on:
  schedule:
    - cron: "15 4 * * *"   # denne o 04:15 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: chrome

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml selenium ics

      - name: Run scraper
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: python Cike_calendar.py

      - name: Create Pull Request with updated events.ics
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Daily events.ics update"
          title: "Daily update: events.ics"
          body: "Automated update of events.ics via scraper"
          branch: ci/ics-auto-update
          add-paths: |
            events.ics
          delete-branch: true
