name: Update calendar daily
on:
  schedule:
    - cron: "0 5 * * *"   # denne o 5:00 UTC (6:00 Bratislava)
  workflow_dispatch:       # mo탑nos큐 spusti큐 ru훾ne

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python Cike_calendar.py

      - name: Commit and push updated ICS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add events.ics
          git commit -m "Daily update" || echo "No changes"
          git push
