name: Build events.ics daily

on:
  schedule:
    - cron: "*/5 * * * *"       # dočasne každé 2 min pre test
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug trigger
        run: |
          echo "event=${{ github.event_name }}"
          echo "utc_now=$(date -u)"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: chrome

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml selenium ics pytz html5lib

      - name: Run scraper
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: python Cike_calendar.py

      - name: Commit updated ICS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add events.ics
          git commit -m "Automated update of events.ics" || echo "No changes to commit"
          git push
